StockWise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_product
from main.views import delete_product
from main.views import get_product_json
from main.views import add_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax')

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    price = models.IntegerField()
    description = models.TextField()
    category = models.CharField(max_length=255)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price","amount", "description", "category"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'products': products,
        'last_login': request.COOKIES['last_login']
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        description = request.POST.get("description")
        category = request.POST.get("category")

        user = request.user

        new_product = Product(name=name,amount = amount, price=price, description=description,category = category, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% block content %}
<style>
    /* CSS yang mengatur tema */
    h1 {
        font-size: 24px;
        color: #583672;
        margin-bottom: 20px;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
    }

    /* CSS untuk formulir */
    form {
        margin-top: 20px;
    }

    /* CSS untuk tabel */
    table {
        background-color: #fff;
        border: 1px solid #ddd;
        border-collapse: collapse;
        width: 50%; /* Mengurangi lebar tabel */
        margin: 0 auto; /* Memusatkan tabel di tengah halaman */
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }

    th, td {
        padding: 8px; /* Mengurangi padding sel dalam tabel */
        text-align: left;
    }

    th {
        background-color: #FEE12B;
        color: #fff;
        font-weight: bold;
    }

    tr:nth-child(odd) {
        background-color: #f2f2f2;
    }

    /* CSS untuk tombol "Edit Product" */
    input[type="submit"] {
        background-color: #000;
        color: #fff;
        padding: 10px 20px;
        font-weight: bold;
        text-transform: uppercase;
        border: none;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #452A5A;
    }
</style>

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
    <style>
        /* CSS untuk latar belakang */
        body {
            background-color: #000;
            font-family: 'Assistant', sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            margin: 0;
        }

        /* CSS untuk kotak login */
        .login-box {
            background-color: #fff;
            border-radius: 8px;
            padding: 20px;
            text-align: center;
            box-shadow:
                0px 2px 10px rgba(0, 0, 0, 0.2),
                0px 10px 20px rgba(0, 0, 0, 0.3),
                0px 30px 60px 1px rgba(0, 0, 0, 0.5);
        }

        /* CSS untuk header */
        .login-header {
            background-color: #FFD300;
            color: #000;
            padding: 10px;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
        }

        .login-header h1 {
            margin: 0;
        }

        /* CSS untuk formulir */
        .login-form {
            margin-top: 20px;
        }

        .login-form input[type="text"],
        .login-form input[type="password"] {
            border: none;
            background: #f2f2f2;
            width: 100%;
            color: #000;
            font-size: 1em;
            outline: none;
            margin-bottom: 20px;
            margin-top: 20px;
            padding: 10px;
            border-radius: 5px;
        }

        /* CSS untuk tombol Login */
        .login-form .btn-login {
            background-color: #FFD300;
            text-decoration: none;
            color: #000;
            border: 2px solid #000;
            padding: 10px 20px;
            font-weight: bold;
            text-transform: uppercase;
            border-radius: 5px;
            transition: background-color 0.5s, color 0.5s;
            display: inline-block;
        }

        .login-form .btn-login:hover {
            background-color: #000;
            color: #fff;
        }

        /* CSS untuk tautan "Register Now" */
        .register-link {
            color: #00f;
            text-decoration: none;
        }

        .register-link:hover {
            text-decoration: underline;
        }

    </style>
{% endblock meta %}

{% block content %}
<div class="login-box">
    <div class="login-header">
        <h1>Login</h1>
    </div>

    <form class="login-form" method="POST" action="">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input class="btn btn-login" type="submit" value="Login">
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Don't have an account yet? <a href="{% url 'main:register' %}" class="register-link">Register Now</a>
</div>


{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block meta %}
    <title>Main</title>
    <style>
        /* Navbar styles */
        .navbar {
            background-color: #452A5A;
            color: #FFD300;
            border-bottom: 2px solid #fff;
            position: fixed;
            width: 100%;
            top: 0;
            left: 0;
            z-index: 1000;
        }

        .navbar-brand {
            color: #FFD300;
            font-size: 32px;
            font-weight: bold;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
        }

        .nav-link {
            color: #fff !important;
            margin-right: 20px;
            font-weight: bold;
            transition: color 0.3s;
        }

        .nav-link:hover {
            color: #452A5A !important;
        }

        /* Menggeser tombol Logout ke ujung kanan */
        .navbar-nav {
            display: flex;
            align-items: center;
        }

        /* Menggeser tombol Logout ke pojok kanan atas */
        .navbar-logout {
            position: absolute;
            top: 0;
            right: 0;
            margin: 20px;
            background-color: #FFD300;
            color: #452A5A;
            padding: 12px 24px;
            font-weight: bold;
            text-decoration: none;
            text-transform: uppercase;
            transition: background-color 0.3s, color 0.3s;
        }

        /* Gaya tombol Logout saat digerakkan */
        .navbar-logout:hover {
            background-color: #452A5A;
            color: #FFD300;
        }

        body {
            background-image: url('background-image.jpg');
            background-size: cover;
            background-repeat: no-repeat;
        }

        /* Page title styles */
        h1, h3, h5 {
            font-size: 24px;
            color: #FFD300;
            padding: 10px 0;
            margin: 0;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
        }

        /* Product table styles */
        table {
            background-color: #fff;
            border: 1px solid #ddd;
            border-collapse: collapse;
            width: 100%;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 12px 20px;
            text-align: left;
        }

        th {
            background-color: #452A5A;
            color: #FFD300;
            font-weight: bold;
        }

        tr:nth-child(odd) {
            background-color: #f2f2f2;
        }

        /* Action buttons styles */
        .btn {
            padding: 10px 20px;
            margin-right: 5px;
            font-weight: bold;
            text-transform: uppercase;
            transition: background-color 0.3s;
            border: none;
            cursor: pointer;
        }

        .btn {
            margin-right: 5px;
        }

        .btn {
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
        }

        .btn-primary {
            background-color: #FFD300;
            color: #452A5A;
        }

        .btn-primary:hover {
            background-color: #452A5A;
            color: #FFF;
        }

        .btn-warning {
            background-color: #452A5A;
            color: #FFD300;
        }

        .btn-warning:hover {
            background-color: #FFD300;
            color: #FFF;
        }

        .btn-danger {
            background-color: #FF6347;
            color: #fff;
        }

        .btn-danger:hover {
            background-color: #E03E26;
        }

        /* Logout button styles */
        .logout-button {
            background-color: #452A5A;
            color: #FFD300;
            padding: 12px 24px;
            font-weight: bold;
            text-decoration: none;
            text-transform: uppercase;
            transition: background-color 0.3s, color 0.3s;
        }

        /* Gaya tombol Logout saat digerakkan */
        .logout-button:hover {
            background-color: #FFD300;
            color: #FFF;
        }

        /* Card styles */
        .card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            margin-top: 20px;
        }

        .card {
            background-color: #452A5A;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
            border-radius: 8px;
            margin: 10px;
            width: calc(33.33% - 20px);
            padding: 20px;
            transition: box-shadow 0.3s;
        }

        .card:hover {
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.4);
        }

        /* Card title */
        .card-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #FFD300;
        }

        /* Card description */
        .card-description {
            font-size: 14px;
            margin-bottom: 15px;
            color: #fff;
        }

        /* Card buttons */
        .card-buttons {
            display: flex;
            justify-content: space-between;
        }

        .card-button {
            background-color: #FFD300;
            color: #452A5A;
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;
            text-transform: uppercase;
            transition: background-color 0.3s;
            display: block;
            margin: 0 auto; /* Mengatur tombol ke tengah */
        }

        .card-button:hover {
            background-color: #452A5A;
            color: #FFD300;
        }

    </style>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">StockWise</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
      </div>
      <div class="navbar-nav">
      </div>
        <div class="navbar-logout">
            <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
        </div>
    </div>
  </div>
</nav>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount">
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="mb-3">
                    <label for="category" class="col-form-label">Category:</label>
                    <input type="text" class="form-control" id="category" name="category"></input>
                    </div>
                </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<h5>Welcome, {{ name }}</h5>
<h3>Product List</h3>

<div id="card-container" class="card-container"></div>


<br />


<a href="{% url 'main:create_product' %}">
    <button class="card-button">Add New Product</button>
</a>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>

<h10>Last Login Session: {{ last_login }}</h10>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json());
    }

    async function refreshProducts() {
    const products = await getProducts();
    const cardContainer = document.getElementById("card-container");
    cardContainer.innerHTML = "";

    products.forEach((item) => {
        // Buat card untuk setiap produk
        const card = document.createElement("div");
        card.classList.add("card");

        const cardTitle = document.createElement("h2");
        cardTitle.textContent = item.fields.name;
        card.appendChild(cardTitle);

        const cardAmount = document.createElement("p");
        cardAmount.textContent = `Amount: ${item.fields.amount}`;
        card.appendChild(cardAmount);

        const cardDate = document.createElement("p");
        cardDate.textContent = `Date Added: ${item.fields.date_added}`;
        card.appendChild(cardDate);

        const cardCategory = document.createElement("p");
        cardCategory.textContent = `Category: ${item.fields.category}`;
        card.appendChild(cardCategory);

        const cardDescription = document.createElement("p");
        cardDescription.textContent = `Description: ${item.fields.description}`;
        card.appendChild(cardDescription);

        // Tambahkan card ke card-container
        cardContainer.appendChild(card);
    });
}


    refreshProducts()

    

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addProduct


</script>


{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    /* CSS dengan tema kuning dan hitam */
    .login {
        background-color: #FFD300; /* Warna latar belakang kuning */
        border: 1px solid #000; /* Garis tepi hitam */
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        width: 50%; /* Mengurangi lebar form */
        margin: 0 auto; /* Memusatkan form di tengah halaman */
    }

    h1 {
        font-size: 24px;
        color: #000; /* Warna teks hitam */
        margin-bottom: 20px;
        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
    }

    form {
        margin-top: 20px;
    }

    table {
        width: 100%;
    }

    td {
        padding: 8px;
    }

    input[type="text"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #000; /* Garis tepi hitam */
    }

    input[type="submit"] {
        background-color: #000; /* Warna latar belakang hitam */
        color: #FFFFFF; /* Warna teks kuning */
        padding: 10px 20px;
        font-weight: bold;
        text-transform: uppercase;
        border: none;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #452A5A; /* Warna latar belakang hitam ketika hover */
    }

    ul {
        list-style-type: none;
        padding: 0;
    }

    li {
        color: #FF6347; /* Warna teks merah */
        font-weight: bold;
    }
</style>

<div class="login">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Daftar"/></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>